version: '3'
name: laravel-project

services:

    # PHP
    php:
        container_name: php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    # Nginx
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 8080:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    # DATABASE (MySQL)
    db:
        container_name: mysql
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/mysql/data:/var/lib/mysql
            - .docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: employees
            MYSQL_USER: phapnd
            MYSQL_PASSWORD: employees
